DICTS_FOLDER <- file.path(ROOT_FOLDER, "data/_metadata/dicts")

FOLDER_RAW_SIMAT <- file.path(ROOT_FOLDER, 'data/1_raw/SIMAT')
FOLDER_RAW_SIMAT_2004 <- file.path(FOLDER_RAW_SIMAT, '2004-2022')
FOLDER_RAW_SIMAT_2017 <- file.path(FOLDER_RAW_SIMAT, '2017-2023')
rm(FOLDER_RAW_SIMAT)

FOLDER_PROCESSED_SIMAT <- file.path(ROOT_FOLDER, 'data/2_processed/SIMAT')
FOLDER_PROCESSED_SIMAT_2004 <- file.path(FOLDER_PROCESSED_SIMAT, '2004-2022')
FOLDER_PROCESSED_SIMAT_2017 <- file.path(FOLDER_PROCESSED_SIMAT, '2017-2023')
rm(FOLDER_PROCESSED_SIMAT)

FOLDER_UNSENSITIVE <- file.path(ROOT_FOLDER, 'data/3_unsensitive')
FOLDER_UNSENSITIVE_SIMAT_2004 <- file.path(FOLDER_UNSENSITIVE, 'SIMAT/2004-2022')
FOLDER_UNSENSITIVE_SIMAT_2017 <- file.path(FOLDER_UNSENSITIVE, 'SIMAT/2017-2023')
rm(FOLDER_UNSENSITIVE)

FOLDER_INDIVIDUALS <- file.path(ROOT_FOLDER, 'data/individuals')