# README

## Tareas pendientes

-   [x] Anonimizar base
-   [ ] Base de estudiantes
    -   [ ] **JD** Modificar código para incorporar nuevas funciones de diccionarios.
    -   [ ] **JD** Detectar calidad de `fake_id` (IDs de acudiente) 
    -   [ ] **MJ** Detectar variables de interés, su uniname (yo lo escojo- Descripción que hay en la variable) y uniclass, porcentaje de años por variable.
    -   [ ] Entity resolution para los originales y crear `PER_ID`.
    -   [ ] Unificar los datos para las variables de interés
    -   [ ] Crear variable de deserción (definición)
    -   [ ] Crear variable de continuidad (misma o diferente institucion)
    -   [ ] Crear variable de repitencia
-   [ ] Base de colegios
    -   [ ] Identificar variables relacionadas con los colegios, su uniname y uniclass
    -   [ ] Unificar
    -   [ ] ¿Crear variable de apertura y cierre?
-   [ ] Modelo de deserción.
    -   [ ] Selección de variables
    -   [ ] Estimación Logit
    -   [ ] Métricas
    -   [ ] Visualización de resultados
    -   [ ] Modelos de pronóstico
-   [ ] Pareo con otras bases
    -   [ ] Fecha de nacimiento con el SISBEN (evaluar calidad)
